# Generated by Django 2.0.5 on 2018-05-05 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='Nit de la Veterinaria')),
                ('nombre', models.CharField(max_length=400, verbose_name='Razon Social')),
                ('telefono', models.CharField(max_length=25, verbose_name='Número de teléfono')),
                ('dirección', models.CharField(max_length=400, verbose_name='Dirección')),
            ],
        ),
        migrations.CreateModel(
            name='Dueño',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=20, unique=True, verbose_name='Numero de identificación')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Responsable')),
                ('numero', models.CharField(max_length=25, verbose_name='Número de Contácto')),
                ('telefono', models.CharField(max_length=25, verbose_name='Teléfono Fijo')),
                ('correo', models.CharField(max_length=500, verbose_name='Correo Eletronico')),
                ('direccion', models.CharField(max_length=500, verbose_name='Dirección')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripción', models.TextField(max_length=200, verbose_name='Nombre del Responsable')),
                ('fecha', models.DateField()),
                ('fecha_v', models.DateField()),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Clinica')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Responsable')),
                ('identificacion', models.CharField(max_length=20, unique=True, verbose_name='Numero de identificación')),
                ('fecha_nacimiento', models.DateField()),
                ('Genero', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], default='M', max_length=1)),
                ('dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Dueño')),
            ],
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=25, unique=True, verbose_name='Cédula')),
                ('targeta_profesional', models.CharField(max_length=50, unique=True, verbose_name='Número de Registro')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Clinica')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Paciente'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='veterinario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Veterinario'),
        ),
    ]
